services:
  - type: web
    name: backend
    env: docker
    dockerContext: ./bank_backend
    dockerfilePath: ./bank_backend/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:file:./data/bankdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.h2.Driver
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.H2Dialect
      - key: SPRING_DATASOURCE_USERNAME
        value: sa
      - key: SPRING_DATASOURCE_PASSWORD
        value: ""
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

  - type: web
    name: frontend
    env: docker
    dockerContext: ./bank_frontend
    dockerfilePath: ./bank_frontend/Dockerfile
